basePath: /
definitions:
  models.Fact:
    properties:
      answer:
        type: string
      question:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: fazilkp2000@gmail.com
    name: API Support
    url: https://fazilnbr.github.io/mypeosolal.web.portfolio/
  description: This is a sample true fact api qustion and answer. You can visit the
    GitHub repository at https://github.com/fazilnbr/learn-docker
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Go + Fiber True fact API
  version: "1.0"
paths:
  /:
    get:
      operationId: listTrueFact
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Fact'
            type: array
      summary: "List True Fact \tQ&A"
      tags:
      - APIs
  /fact:
    post:
      operationId: createTrueFact
      parameters:
      - description: admin login
        in: body
        name: Fact
        required: true
        schema:
          $ref: '#/definitions/models.Fact'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Fact'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/models.Fact'
      summary: "Create True Fact \tQ&A"
      tags:
      - APIs
swagger: "2.0"
